spring:
  datasource:
    url: jdbc:mysql://localhost:3308/springboot3?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2b4c6b1a5ba829c6ac9f10c98e5b3e28a8970b44ddafeab148dafcbdc34c015a
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: false

cpsd:
  ap:
    decrypt-key: template
    salt: 123456

jwt:
  secret-key: template
  access-token-validity: 4

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

log:
  path: C:/log/template/prod

