server:
  servlet:
    #context-path: /template
    session:
        cookie:
          secure: true
          same-site: Strict
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/springboot3?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2b4c6b1a5ba829c6ac9f10c98e5b3e28a8970b44ddafeab148dafcbdc34c015a
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  thymeleaf:
    cache: false

jwt:
  secret-key: template
  access-token-validity: 4

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

        #logging:
        #  level:
        #    root: info
        #    org:
        #      hibernate:
        #        SQL: debug
        #        type:
        #          descriptor:
        #            sql:
        #              BasicBinder: trace

#http://localhost/template/swagger-ui/index.html
#http://localhost/template/api/sample/getAll1
#http://localhost/template/backend/login
cpsd:
  ap:
    decrypt-key: template
    salt: 123456

template:
  entry-point:
    auth: backend

project:
  host: http://127.0.0.1
  path: /template
  server-url: ${project.host}${project.path}/

log:
  path: C:/log/template