server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:mykeystore.jks
#    key-store-type: JKS
#    key-store-password: Qwer3wer
#    key-alias: mysslcert
  address: 127.0.0.1
  servlet:
    session:
        cookie:
          secure: true
          same-site: Strict
  port: 8082

spring:
  profiles:
    active: sit
  thymeleaf:
    cache: false

template:
  entry-point:
    auth: backend

project:
  host: ${PROJECT_HOST:https://localhost:443}
  path: ${PROJECT_PATH:/template}
  server-url: ${project.host}${project.path}/
